# AUTHENTICATED
quarkus.http.auth.permission.health.paths=/q/*
quarkus.http.auth.permission.health.policy=permit
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated

#fallback default tenantId
tkit.rs.context.tenant-id.enabled=true
tkit.rs.context.tenant-id.default=default

#S3 API Client Configuration
%prod.quarkus.s3.aws.credentials.type=static
%prod.quarkus.s3.aws.credentials.static-provider.access-key-id=${onecx.file.storage.s3-client.access-key-id}
%prod.quarkus.s3.aws.credentials.static-provider.secret-access-key=${onecx.file.storage.s3-client.secret-access-key}
%prod.quarkus.s3.endpoint-override=${onecx.file.storage.s3-client.endpoint}
%prod.quarkus.s3.aws.region=${onecx.file.storage.s3-client.region}

%dev.onecx.file.storage.bucket=onecx
%dev.quarkus.s3.aws.credentials.static-provider.access-key-id=rustfsadmin
%dev.quarkus.s3.aws.credentials.static-provider.secret-access-key=rustfsadmin
%dev.quarkus.s3.endpoint-override=http://s3.eu-central-1.amazonaws.com
%dev.quarkus.s3.aws.region=eu-central-1

%test.quarkus.s3.devservices.buckets=onecx
%test.onecx.file.storage.s3-client.access-key-id=rustfsadmin
%test.onecx.file.storage.s3-client.secret-access-key=rustfsadmin
%test.onecx.file.storage.s3-client.endpoint=http://s3.eu-central-1.amazonaws.com
%test.onecx.file.storage.s3-client.region=eu-central-1

# required for local rustfs development
#quarkus.s3.path-style-access=true

# BUILD
quarkus.openapi-generator.codegen.input-base-dir=target/tmp/openapi

# OIDC
%prod.quarkus.oidc-client.client-id=${quarkus.application.name}

# INTEGRATION TEST
quarkus.test.integration-test-profile=test

# TEST
%test.quarkus.http.test-port=0
%test.tkit.log.json.enabled=false

%test.tkit.rs.context.token.header-param=apm-principal-token
%test.tkit.rs.context.token.enabled=true
%test.tkit.rs.context.tenant-id.enabled=true
%test.tkit.rs.context.tenant-id.mock.enabled=true
%test.tkit.rs.context.tenant-id.mock.data.org1=100
%test.tkit.rs.context.tenant-id.mock.claim-org-id=orgId
%test.quarkus.keycloak.devservices.roles.alice=role-admin
%test.quarkus.keycloak.devservices.roles.bob=role-user
%test.quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
%test.quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
%test.quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}

# PIPE CONFIG

